### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by HenricoLega** [ofeksadlo/chess-cheat#13]
Man I do every thing if you talk to I do but I dont now to how start program. Please help meeeee

**Comment by ofeksadlo** [comment]
Describe to me what happens when you open the program?

**Comment by HenricoLega** [comment]
I am start the main.py but he close at the same time

**Comment by ofeksadlo** [comment]
Instead of opening the main.py
Run a cmd on the repository path
And execute main.py by typing: `python main.py`
Then you'll be able to see the exception that makes
the program crash.

Just so you know this is for educational purposes.
So you'll have hard time setting it up. Without any
former knowledge of python.

**Comment by HenricoLega** [comment]
Traceback (most recent call last):
  File "C:\Users\Henrico\Desktop\Nova pasta\lichess-cheat-master\main.py", line 374, in <module>
    turnImg = screenshot(region=(1335, 665,10,16))
  File "C:\Python39\lib\site-packages\pyscreeze\__init__.py", line 143, in wrapper
    raise PyScreezeException('The Pillow package is required to use this function.')
pyscreeze.PyScreezeException: The Pillow package is required to use this function.








when I start the program and choose a color and this happen whats is the  problem??

**Comment by ofeksadlo** [comment]
> Traceback (most recent call last):
> File "C:\Users\Henrico\Desktop\Nova pasta\lichess-cheat-master\main.py", line 374, in
> turnImg = screenshot(region=(1335, 665,10,16))
> File "C:\Python39\lib\site-packages\pyscreeze__init__.py", line 143, in wrapper
> raise PyScreezeException('The Pillow package is required to use this function.')
> pyscreeze.PyScreezeException: The Pillow package is required to use this function.
> 
> when I start the program and choose a color and this happen whats is the problem??

You obviously missing the [Pillow module](https://pypi.org/project/Pillow/)

**Comment by lilhackerman12** [comment]
Hey, can you explain how do I run liechess cheat script. I have stockfish but dont know how to execute it
